"""Adopt generated PDF highlights without confusing them with user annotations."""

from __future__ import annotations

import hashlib
from collections import Counter

import fitz

from .highlighter import HIGHLIGHT_COLORS
from .reader_geometry import normalized, rect, selection_parts


def embedded_ai_highlights(path, document_id, index):
    result = []
    occurrences = Counter()
    origin_pages = index.get("origin_pages", [])
    with fitz.open(path) as pdf:
        for page in pdf:
            for mark in page.annots() or []:
                info = mark.info
                category, quote = info.get("title"), info.get("content", "").strip()
                if mark.type[0] != fitz.PDF_ANNOT_HIGHLIGHT or category not in HIGHLIGHT_COLORS:
                    continue
                points = mark.vertices or []
                if not points or len(points) % 4 or not info.get("id"):
                    continue
                geometry = {
                    "pageIndex": page.number,
                    "rect": rect(mark.rect),
                    "segmentRects": [rect(fitz.Quad(points[i : i + 4]).rect) for i in range(0, len(points), 4)],
                }
                if not quote:
                    quote = " ".join(p["quote"] for p in selection_parts(index, geometry)).replace("\x00", "").strip()
                if not quote:
                    continue
                origin = origin_pages[page.number] if page.number < len(origin_pages) else page.number
                # Names generated by PyMuPDF and xrefs change when archiving or
                # combining PDFs. Meaning + source page survives those changes.
                key = (document_id, origin, category, normalized(quote))
                occurrence_key = (page.number, category, normalized(quote))
                ordinal = occurrences[occurrence_key]
                occurrences[occurrence_key] += 1
                aid = "ai_" + hashlib.sha256(repr((*key, ordinal)).encode()).hexdigest()[:40]
                rgb = mark.colors.get("stroke") or HIGHLIGHT_COLORS[category]
                color = "#" + "".join(f"{round(c * 255):02x}" for c in rgb[:3])
                result.append(
                    {
                        "key": aid,
                        "annotation_id": aid,
                        "data": {
                            "id": info["id"],
                            "type": 9,
                            **geometry,
                            "color": color,
                            "opacity": mark.opacity if mark.opacity >= 0 else 1,
                            "contents": quote,
                            "author": category,
                            "subject": "AI 重点",
                        },
                    }
                )
    return result
